### ISSUE TITLE
Support bean validation annotations @FutureOrPresent and @PastOrPresent

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1538]
### Environment

- Platform version: 7.0
- Client type: Web

### Description of the bug or enhancement

Implement support for `PastOrPresent` and `FutureOrPresent` annotations in DatePicker and DateField

**Comment by Mihail063** [comment]
After adding `@FutureOrPresent` annotation to the attribute with Date type and select the present date, shows alert messages "must be in the future or in the present"

**Comment by pribavkindenis** [comment]
It's O.K. in many cases. 

The annotation JavaDoc says: the notion of present here is defined relatively to the type on which the constraint is used. For instance, if the constraint is on a `java.time.Year`, present would mean the whole current year.

For instance, if you use DatePicker UI component with the Entity attribute below then if you select the present date,  `com.haulmont.cuba.web.gui.components.WebDatePicker#convertToModel` method sets the time of the present date to `LocalTime.MIDNIGHT` (which is 00:00). That means when you try to validate the component and current time is greater than 00:00, the validation process will fail.
```java
@FutureOrPresent
@Temporal(TemporalType.DATE)
protected java.util.Date someDate;
```
To solve this problem you could use `java.time.LocalDate` type instead of `java.util.Date` or DateField UI component instead of DatePicker.
