### ISSUE TITLE
CheckBoxGroup displays incorrectly when screen opening

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1661]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

1. Create an entity with MANY_TO_MANY association
2. Data model:
```
@Entity(name = "radiobtn_Team")
public class Team extends StandardEntity {
. . .
    @JoinTable(name = "RADIOBTN_TEAM_EMPLOYEE_LINK",
            joinColumns = @JoinColumn(name = "TEAM_ID"),
            inverseJoinColumns = @JoinColumn(name = "EMPLOYEE_ID"))
    @ManyToMany
    protected List<Employee> members;
. . .
}
```

WTR:
- Import the project attached
- Create a new team or edit the existing one:
![checkBox.gif](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/6270ecb5-eb0a-45b2-8207-da3d1fbf2d7a)

[radio-btn.zip](https://github.com/cuba-platform/cuba/files/2663427/radio-btn.zip)

**Comment by Flaurite** [comment]
Depends on: https://github.com/vaadin/framework/issues/11486

**Comment by web-devel** [comment]
I think there is no proper `fix` for this due to dynamic nature of options.
One approach to avoid flickering is specifying height of CheckBoxGroup explicitly:

```xml
<checkBoxGroup dataContainer="teamDc" property="members" optionsContainer="employeesCt" height="100px"/>
```
Currently, the issue with this approach is that component height grows exceeding specified amount:
 ![checkgroupbox.png](https://images.zenhubusercontent.com/5aeaf58f4b5806bc2bd19c13/8c131c3b-df87-4150-9b73-f4aab6e16137)

We can consider adding `overflow:auto` to container so that the component will preserve it's height:
![image.png](https://images.zenhubusercontent.com/5aeaf58f4b5806bc2bd19c13/190c431a-286f-4637-b872-d07930472f98)

**Comment by dtsaryov** [comment]
The glitch that is demonstrated in issue is caused by `FieldGroup` rendering:

![image](https://user-images.githubusercontent.com/6183810/66578004-6345a180-eb8b-11e9-8e22-6e4c340c6ecf.png)

Everything is ok when `CheckBoxGroup` is not in `FieldGroup`:

https://recordit.co/XOmsEPYkFR
