### ISSUE TITLE
ResourceView doesn't refresh its content if FileDescriptorResource with the same names are used

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1922]
### Environment

- Platform version: 6.8

### Test project

You can use the following project instead of RefApp. 

The archive contains few files with the same names to test the issue (`test-pictures` folder).

[resource-change-test.zip](https://github.com/cuba-platform/cuba/files/2924737/resource-change-test.zip)

### Description of the bug or enhancement

- Minimal reproducible example

1. Prepare few files with the same names
2. Upload them into RefApp
![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/0af52e1f-2496-438f-8777-2ecb579c6f92)
3. Open `Image` component sample (Menu -> Tests -> Component Samples -> Image)
4. Try to set different `FileDescriptor`s

- Expected behavior

`Image` content is updated

- Actual behavior

The same content for different `FileDescriptor`s

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/54d23b65-f237-44cf-96d5-b0383e2eaecd)

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/737156a4-398a-415f-9a0a-f96b35d44aaa)

**Comment by tausendschoen** [comment]
In my opinion the implementation was initially correct. Think about the case:
* if you upload a file, and the file ist stored in the DB. It gets a UUID to identify it.
* if you deliver the file to a browser, the UUID of the file should be appended, to be able to distinguish files with the same name 

If you change the content of the file descriptor, a browser or a http server, that chaches files will deliver the old file, until the expiration date is set or the cache is cleared. To append here a random UUID is the wrong approach, because no browser or http server will be able to cache the content.

The correct way to programm is to create a new file and not to change the content of the file descriptor.
