### ISSUE TITLE
Item of 2nd level of composition is not removed if root entity was not loaded with it

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#1951]
### Environment

- Platform version: 7.0.2

### Description of the bug or enhancement

We have an `Order` entity. It has a collection of `OrderItem` (composition). Each `OrderItem` has a collection of `OrderItemParam` (composition). 

When I open the `Order `entity, open some `OrderItem` editor and remove one of existing `OrderItemParam`, then this param will not be removed from the database when I save the `Order`

A project where it can be reproduced: 
[comp-test.zip](https://github.com/cuba-platform/cuba/files/2960949/comp-test.zip)

**Comment by knstvk** [comment]
The issue reproduced only if Order was loaded with local view of OrderItem, i.e. without OrderItemParam list. In general, this is not correct - the composition should be loaded to the full depth. However, the fix should save from such mistakes because now DataContext can remove entity even if it doesn't contain it.
