### ISSUE TITLE
Dynamic attributes improvements

### ISSUE THREAD

**Issue by ovchinnikovsp** [cuba-platform/cuba#2190]
1. Support of decimal values
  - decimals count
  - format 
2. Ability to setup Min and Max value for the numeric attributes
3. Ability to setup custom validator (class or might groovy script)
4. Ability to setup column settings
   - Specify column where the dynamic attr should be shown
   - Order and Align inside the column 
   - For each column need the ability to setup width (%, pixels)

**Comment by andreysubbotin** [comment]
Store configuration as a JSON in a separate column.

**Comment by invviz** [comment]
New issue for custom number format for BigDecimal dynamic attribute was created: #2235

**Comment by invviz** [comment]
New issue was created for the fourth paragraph (Ability to setup column settings) : #2310

**Comment by invviz** [comment]
For QA: 
For all numeric types, it became possible to specify the minimum and maximum value.


For all types of dynamic attributes, it became possible to specify a validation Groovy script to verify the value entered by the user. In case of failed validation a Groovy script should return error message. Otherwise a script should not return any value or return null. The value is available in the script by the value macro. For error message it uses Groovy string and it is possible to use '$value' key for formatted output.

For example:
```
if (!value.startsWith("correctValue")) return "the value '\$value' is incorrect"
