### ISSUE TITLE
Ability to setup custom format for Decimal dynamic attributes

### ISSUE THREAD

**Issue by invviz** [cuba-platform/cuba#2235]
### Environment

- Platform version: 7.1 

### Description of the bug or enhancement

Add ability to specify custom number format for BigDecimal dynamic attributes.

This issue should be implemented after #2190.

**Comment by invviz** [comment]
The use of custom format for Decimal dynamic attributes is available only for the new Screen API. Supported web components: Table, Form, DataGrid, DynamicAttributesPanel.

**Comment by Mihail063** [comment]
Case 1
1. Create a new entity with browser and editor screen
2. Start the project 
3. Start to create a new dynamic attribute 
4. Add number format pattern %###.## or ##.##%
5. Save the dynamic attribute for the entity browser and editor screen
6. Open the entity editor
7. Enter some number and try to save the instance 

Expected behavior 
Multiply by 100 and show in percent should be applied automatically.

Actual behavior 
A notification appears that Wrong format

Case 2
1. Create a new entity with browser and editor screen
2. Start the project 
3. Start to create a new dynamic attribute 
4. Add number format pattern ‰###.## or ###.##‰
5. Save the dynamic attribute for the entity browser and editor screen
6. Open the entity editor
7. Enter some number and try to save the instance 

Expected behavior 
Multiplied by 1000 and displays a mile should be applied automatically.

Actual behavior 
A notification appears that Wrong format

Case 3
1. Create a new entity with browser and editor screen
2. Start the project 
3. Start to create a new dynamic attribute 
4. Add number format pattern ###.##¤ or ¤###.##
5. Save the dynamic attribute for the entity browser and editor screen
6. Open the entity editor
7. Enter some number and try to save the instance 

Expected behavior 
Currency sign should be replaced by a currency symbol automatically

Actual behavior 
A notification appears that Wrong format
![image](https://user-images.githubusercontent.com/24281695/61452579-26438780-a96d-11e9-9c68-1f942075cdaa.png)

**Comment by invviz** [comment]
This is the expected behavior. When using a custom format, the prefix and suffix must be entered manually.

The same behavior occurs when using the NumberFormat annotation.
