### ISSUE TITLE
Move dialogMode to facets

### ISSUE THREAD

**Issue by aleksey-stukalov** [cuba-platform/cuba#2305]

**Comment by GlebDurygin** [comment]
We cannot replace `dialogMode` XML element and `@DialogMode` annotation with a facet because  it cannot be considered as a facet.
The documentation says:
>Facets are screen elements that are not added to the screen layout, unlike visual components. Instead, they add supplementary behavior to the screen or one of its components.

But this facet is not a screen element, it only controls the display of the dialog screen during screen loading. At other times, this facet is unavailable and is of no use. 

Also, if we remove the `@DialogMode` annotation, then we lose the ability to create dialog screens that only have a screen controller. Since the window object is created before the facets are loaded.
