### ISSUE TITLE
Validation and parsing problem for double config value and ru locale

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2343]
### Environment
- Platform version: 7.0
- Locale: any locale with decimalSeparator differing from ".", for example Russian.

### Description of the bug or enhancement
Can be reproduced on refapp demo: http://cubadev:9070/app/#login

- Login under *Russian* locale into refapp
- Open Администрирование -> Свойства приложения
- Search for "zoom" 
- Open "charts.map.defaultZoom" for editing
- Input "7,5" with comma separator  - which is a configured decimal separator for ru locale
- Press OK

Expected: we either get validation error, or auto-conversion from 7,5 to 7.5, or 7,5 value is saved as is.

Actual: validation does not trigger. After value is saved, we see NumberFormatException instead of value:
![image](https://user-images.githubusercontent.com/6158807/62770615-6dc0bd80-baac-11e9-9b77-2a9b18881bc3.png)

This forum problem is probably related to the same source code:
https://www.cuba-platform.ru/discuss/t/sbros-porta-pri-nastrojke-v-application-properties/3363/10

## Updates
The application properties with decimal type support the user locale settings.

## QA
* Check the above case
* Check decimal (double or float) app property setting in different locales

**Comment by sukhova** [comment]
Tested on the 7.0-SNAPSHOT

Test case 1:
* Login under Russian locale into refapp
* Open Администрирование -> Свойства приложения
* Search for `zoom`
* Open `charts.map.defaultZoom` for editing
* Input `7,5` with comma separator - which is a configured decimal separator for ru locale
* Press OK
* Open `charts.map.defaultZoom` for editing
* Input `7.5` with comma separator 

**AR**:
Actual: validation does not trigger. After value is saved, we see `NumberFormatException` instead of value

**Comment by GlebDurygin** [comment]
Fix validation problem with decimal config value. The config values are displayed in application locale.
For example, for the Russian locale, you will need to enter a number with a comma (",") delimiter. For English locale, you will need to enter a decimal number with a dot (".") separator.

**Comment by sukhova** [comment]
1) Open **Administration**-> **Application Properties**
2) Search for `zoom`
3) Open `charts.map.defaultZoom` for editing
4) Enter any symbol value
5) Press OK

**AR**:
Validation does not trigger. After the value is saved, we see NumberFormatException instead of value

**ER**:
Validation for the input field should work
For example, as for property charts.map.defaultLongitude:
![87](https://user-images.githubusercontent.com/40686909/63932557-77fd2880-ca68-11e9-9aa3-271435074fda.png)
