### ISSUE TITLE
Make Calendar component event API consistent and strongly typed

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#2402]
### Environment

- Platform version: 7.2-SNAPSHOT

### Description of the bug or enhancement

In the Calendar component, we have a number of events regarding to event manipulation:
* CalendarEventClickEvent
* CalendarEventResizeEvent
* CalendarEventMoveEvent

The two first events have ```getEntity()``` method that returns an underlying entity. But the last one does not have this method. Therefore, we need to write something like this:

```
    private void onVisitsCalendarCalendarEventMove(Calendar.CalendarEventMoveEvent event) {
        if (!(event.getCalendarEvent() instanceof EntityCalendarEvent)) {
            return;
        }
        Visit visit = ((EntityCalendarEvent<Visit>)event.getCalendarEvent()).getEntity();
        visit.setVisitDate(event.getNewStart());
    }
```
Which is not convinient and looks inconsistent, because for other event I should write:
```
    private void onVisitsCalendarCalendarEventClick(Calendar.CalendarEventClickEvent event) {
        Visit vist = (Visit) event.getEntity();
    }
```

Moreover, even ```getEntity()``` method returns generic ```Entity``` for ```CalendarEventClickEvent ``` and ```CalendarEventResizeEvent```, but not a particular class. Would it be possible to make this method parameterized across all Calendar Event API?:
```
@Nullable
T <T extends Entity>getEntity()
```
So there is no fuss with type casts anymore.

**Comment by Flaurite** [comment]
### Changes

`Calendar#CalendarEventMoveEvent` now has:
```
Entity getEntity();
```

Concerning parameterizing these methods. It is not implemented because `Calendar` and its event classes are not parameterized and it would violate the general concept and style of the component.

### For QA
Check `Calendar#CalendarEventMoveEvent`, `Calendar#CalendarEventClickEvent`, `Calendar#CalendarEventResizeEvent` that they work as expected and try to get entity.
