### ISSUE TITLE
New login window

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/cuba#2455]
There is an idea to provide new login window so that it will be possible to apply branding easily.
Here is a draft:
![login-draft](https://user-images.githubusercontent.com/3295727/65869304-3f17e280-e38b-11e9-8e10-2abdb53b2eed.png)

Example of custom branding:
![login-customized](https://user-images.githubusercontent.com/3295727/65869338-4fc85880-e38b-11e9-9dc4-c1ef432dac42.png)

**Comment by stefanofalasca** [comment]
wonderful

**Comment by clumsym76** [comment]
👍

**Comment by Flaurite** [comment]
## Changes
### Template
New Login Screen will be provided as a template in CUBA Studio. Given template will have the following file structure:

**Screen package**:
- login-screen.xml
- LoginScreen.java

**_web_ folder:**
- VAADIN/login_folder/background.svg
- VAADIN/login_folder/cuba-icon-login.png
- VAADIN/login_folder/login.css

Default names of controller, screen and  resources can be changed.

## Changes in CUBA
Created new bean `LoginScreenAuthDelegate`. It contains common functionality that was replaced from `LoginScreen` and `AppLoginWindow`:
1) Do login
2) Remember me login
3) Set/reset remember me cookies
4) Replaced AuthInfo class

**Migration compatibility**
Due to `AuthInfo` was replaced to `LoginScreenAuthDelegate` users which extend this class or overrides methods with `AuthInfo` type parameters will have to set correct import for the class.

### QA
Template will be tested within Studio issue.
For changes in CUBA we need to make sure that we do not break the following issue: https://github.com/cuba-platform/cuba/issues/2163
