### ISSUE TITLE
Persistent XSS attack through filter name field

### ISSUE THREAD

**Issue by bernatgs** [cuba-platform/cuba#2512]
### Environment

- Platform version: 6.10.7 

- Client type: Web
- Browser: tested in Firefox and Chrome

### Description of the bug or enhancement

- Login and navigate to _Reports > Reports_, _Administration > Users_ or any other page with a filter that can be saved
- Click on the Filter gear and choose _Save as_
- In the filter name field, type `<img src=x onerror="alert('persistent XSS attack')";>`
- Click _OK_

![image](https://user-images.githubusercontent.com/5872879/67779791-713d6280-fa65-11e9-9ec7-e60a2fbd588e.png)

- Expected behavior: nothing happens
- Actual behavior: javascript code is executed

![image](https://user-images.githubusercontent.com/5872879/67779591-23c0f580-fa65-11e9-8cb0-f3cebb73c53b.png)

Related: https://github.com/cuba-platform/reports/issues/140

**Comment by alexbudarov** [comment]
@bernatgs Why are you using such an old release to reproduce the bug? The latest is 6.10.13.

Wasn't this fixed in the https://github.com/cuba-platform/documentation/blob/release_6_10/content/release_notes/issues/release_6.10.9.md ?

Works fine on 6.10 snapshot:
![image](https://user-images.githubusercontent.com/6158807/67835501-92549080-fb03-11e9-8567-8e2900be403b.png)

**Comment by bernatgs** [comment]
Sorry, an outdated project caused the misunderstanding.
