### ISSUE TITLE
DateField value not refresh after entering invalid date

### ISSUE THREAD

**Issue by eartamonov** [cuba-platform/cuba#2682]
- Platform version: 7.1.0
- Client type: Web
- Browser: Chrome

Entity has Date property with annotation @Future
DateField in edit screen is required.
In edit screen we select valid date with DatePicker, after enter in DateField invalid date value (without use DatePicker)

Actual behavior: show "Out of range" error message. Invalid date showing in DateField. But in InstanceContainer item stay first entered(valid) date value. ValueChangeEvent didn't ivoke

Expected behavior: show "Out of range" error message. DateField is clean after enter invalid date

note: same behavior for @Past

**Comment by web-devel** [comment]
This was a deliberate change of behavior since version 7. We leave the value so that user can realize what is wrong with it and easily fix it, rather then re-enter the whole value again.
If you prefer to clear the field you can implement it manually in screen controller by subscribing to `ValidationEvent`.
