### ISSUE TITLE
Web Button and LinkButton has broken UI when hidden and displayed again

### ISSUE THREAD

**Issue by vao-igel** [cuba-platform/cuba#3035]
### Environment

- Platform version: 6.10-SNAPSHOT
- Client type: Web
- Operating system: Windows

### Description of the bug or enhancement

Bug occures on Web and concerns switching visibility of Button and LinkButton.

Steps to reproduce:
- switch button's visibility to false
- force UI repaint by UI.getCurrent().push()
- switch button's visibility to true

Expected behavior: button is displayed the way it was before switching

Actual behavior: button or linkButton is displayed as empty button without icon or caption.

Sample project is attached as patch for CUBA repository.
[WebUI_buttons_bug.patch.zip](https://github.com/cuba-platform/cuba/files/5225568/WebUI_buttons_bug.patch.zip)

**Comment by glebfox** [comment]
Hi @vao-igel,

Could you please clarify why you need to use the `UI.getCurrent().push()` method?

**Comment by vao-igel** [comment]
There's a form which initiates a very long process on server-side when submitted. During this process the form must be in read-only state. If the process succeeds the form is closed, but if there was an exception the form must be returned to editable state with all the data in it.

**Comment by glebfox** [comment]
I'd recommend overriding the submit action so that it won't close the screen, instead, it'll disable the UI and start a background task that performs a very long process without blocking the UI, thus you don't need to use `UI.getCurrent().push()` in order to update components' state. 

Regarding the problem that is appeared when using `UI.getCurrent().push()`, there is nothing we can do, as this is a Vaadin 7 bug.
