### ISSUE TITLE
Dates between 27/03-30/04 are not marked on calendar panel

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#397]
Change PC locale to UTC+2 Beirut to reproduce. The problem occurs yearly within the same date range.

---
Original issue: https://youtrack.haulmont.com/issue/PL-8915

**Comment by PolinaSannikova** [comment]
Note: the issue is still reproduced on cuba version 6.10.15 on Web Client (may need to clear browser cache after changing the timezone to UTC +2 Beirut on PC).
![image](https://user-images.githubusercontent.com/24522994/78231675-3e037180-74e4-11ea-9585-bd8d97d0d2bc.png)
Just wanted to check if there were any news regarding this issue.

**Comment by alexbudarov** [comment]
they don't 5.6 anymore, only 6.10
