### ISSUE TITLE
Simplify creation of composite components based on existing platform components

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#467]
Provide easy way to create custom composite components and write tutorial for that

Relates to #289

**Comment by glebfox** [comment]
# Description

`com.haulmont.cuba.web.gui.components.CompositeComponent` - base class for composite components 

Each `CompositeComponent` must have the **root** component. The **root** component can be either created programmatically or loaded from the XML descriptor file.

## Declarative layout

In order to define composite component layout declaratively, the `@CompositeDescriptor` annotation must be used. It provides a path to the XML descriptor. If the value contains a file name only (i.e. don't start with '/'), it is assumed that the file is located in the package of the composite component class.

```
@CompositeDescriptor("/com/company/test/web/gui/components/comments/commentary-panel.xml")
public class WebCommentaryPanel extends CompositeComponent<VBoxLayout>
```

```
@CompositeDescriptor("stepper-field.xml")
public class WebStepperField extends CompositeComponent<CssLayout>
```

The content of composite component descriptor must conform to the following rules: 
1. Can be only one root component
2. The root element can be wrapped with the `composite` element with `xmlns="http://schemas.haulmont.com/cuba/screen/composite.xsd"`, e.g

```
<composite xmlns="http://schemas.haulmont.com/cuba/screen/composite.xsd">
...
</composite>
```

```
<composite xmlns="http://schemas.haulmont.com/cuba/screen/composite.xsd">
    <cssLayout id="stepper_rootBox" width="100%" stylename="v-component-group stepper-field">
        <textField id="stepper_valueField" width="100%"/>
        <button id="stepper_upBtn"
                icon="font-icon:CHEVRON_UP"
                stylename="stepper-btn icon-only"/>
        <button id="stepper_downBtn"
                icon="font-icon:CHEVRON_DOWN"
                stylename="stepper-btn icon-only"/>
    </cssLayout>
</composite>
```

## Programmatic layout

The `UiComponents` bean can be injected and used to create a layout of a composite component. 

The most preferable place to create a composition is `CreateEvent` listener, e.g.:

```
public WebCommentaryPanel() {
    getEventHub().subscribe(CreateEvent.class, event -> {
        if (getComposition() == null) {
            createComponent();
        }
        ...
    });
}
```

In this case, we can check whether the composition has been created without overriding methods of the superclass.

## CreateEvent

The `CreateEvent` is fired right before the composite component instance is returned by `UiComponent` bean. By this time a composite component is created, has context, all beans are injected and composition is loaded from descriptor if present. That's why the `CreateEvent` listener is the most preferable place to create a composition.

## Helpful interfaces

* `CompositeWithCaption` - provides default implementation for the `Component.HasCaption` interface.
* `CompositeWithContextHelp` - provides default implementation for the `HasContextHelp` interface.
* `CompositeWithDescription` - provides default implementation for the `Component.HasDescription` interface.
* `CompositeWithHtmlCaption` -  provides default implementation for the `HasHtmlCaption` interface.
* `CompositeWithHtmlDescription` - provides default implementation for the `HasHtmlDescription` interface.
* `CompositeWithIcon` - provides default implementation for the `Component.HasIcon` interface.

## AttachNotifier

Starting from now, all UI components (including `CompositeComponent`) implements the `AttachNotifier` interface. This means that they publish `AttachEvent` and `DetachEvent`

* `AttachEvent` - is fired when a component has been attached to a window, i.e. one of the components in parent hierarchy is a window.
* `DetachEvent` - is fired when a component has been detached from a window.

# Examples

[composite-test.zip](https://github.com/cuba-platform/cuba/files/3131046/composite-test.zip)

The project above contains two composite components.

* `WebStepperField` - implements the `Field` interface, i.e. can be used as a field and bind to a value source.
* `WebCommentaryPanel` - contains `DataGrid` associated with `MetaClass`. Additionally, the layout can be created programmatically in case `@CompositeDescriptor` is commented (or removed).

**Comment by ZuperKeurZ** [comment]
Great news to see to progress on this issue!

I hope to be able to test this as soon as I can. Just need to chop off some other dragon heads first :)
