### ISSUE TITLE
Having default values for ServerConfig#getKeyForSecurityTokenEncryption, ServerConfig#getTrustedClientPassword is not fool-proof

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#876]
### Description of the bug or enhancement
Property ServerConfig#getKeyForSecurityTokenEncryption has default value "CUBA.Platform" which allows you to set up and use attribute security without configuring anything.

This is dangerous because one can set up attribute security and start using it on production, without even knowning that he should change encryption key and keep it in secret.

The same thing with "cuba.trustedClientPassword". It also has default value set in xxx-app.properties. I'm not sure that people who use trusted authentication don't forget to change it in their projects or production environment. But situation with trusted password is better because trusted authentication is also protected by IP mask.

see also https://github.com/cuba-platform/documentation/issues/137

**Comment by knstvk** [comment]
Added WARN log message if cuba.keyForSecurityTokenEncryption has default value. It should be rare case because Studio generates random key for each new project.

Trusted access is restricted by localhost by default, so cuba.trustedClientPassword can be a default.  If a user changes IP restrictions, he will also change the password - we'll make it clear in the docs.
